import { Command } from "commander";
import * as fs from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline";
import { ensureConfigDir, getConfigDir, DEFAULT_CONFIG_PATH, expandHome, loadConfig } from "../../config/loader.js";
import { HealthMonitor } from "../../health/monitor.js";

function ask(rl: readline.Interface, question: string, defaultValue?: string): Promise<string> {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

function detectPort(): number {
  try {
    const configPath = expandHome("~/.openclaw/openclaw.json");
    if (fs.existsSync(configPath)) {
      const raw = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      if (raw?.gateway?.port) return raw.gateway.port;
    }
  } catch { /* ignore */ }
  return 3000;
}

function generateToml(opts: {
  port: number;
  memoryThresholdMb: number;
  channels: { type: string; [key: string]: string | number }[];
}): string {
  let toml = `# OpenClaw Aegis Configuration
# Generated by 'aegis init'

[gateway]
configPath = "~/.openclaw/openclaw.json"
pidFile = "openclaw-gateway.service"
port = ${opts.port}
logPath = "~/.openclaw/logs/gateway.log"
healthEndpoint = "/health"

[monitoring]
intervalMs = 10000
probeTimeoutMs = 5000

[health]
memoryThresholdMb = ${opts.memoryThresholdMb}
cpuThresholdPercent = 90
diskThresholdMb = 100

[recovery]
l1MaxAttempts = 3
l2MaxAttempts = 2

[backup]
maxKnownGood = 5
knownGoodStabilityMs = 60000

[deadManSwitch]
enabled = true
countdownMs = 30000

[platform]
type = "systemd"
`;

  if (opts.channels.length > 0) {
    toml += "\n[alerts]\n";
    for (const ch of opts.channels) {
      toml += "\n[[alerts.channels]]\n";
      for (const [key, val] of Object.entries(ch)) {
        if (typeof val === "number") {
          toml += `${key} = ${val}\n`;
        } else {
          toml += `${key} = "${val}"\n`;
        }
      }
    }
  }

  return toml;
}

export const initCommand = new Command("init")
  .description("Interactive setup wizard — configure Aegis for your gateway")
  .option("--auto", "Auto-detect everything, no prompts")
  .action(async (opts: { auto?: boolean }) => {
    const configDir = getConfigDir();
    const configFile = expandHome(DEFAULT_CONFIG_PATH);

    if (fs.existsSync(configFile) && !opts.auto) {
      const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
      const overwrite = await ask(rl, "Config already exists. Overwrite? (y/N)", "n");
      if (overwrite.toLowerCase() !== "y") {
        console.log("Aborted.");
        rl.close();
        return;
      }
      rl.close();
    }

    const detectedPort = detectPort();
    const channels: { type: string; [key: string]: string | number }[] = [];

    if (opts.auto) {
      // Auto mode: detect everything, no prompts
      console.log("Auto-detecting configuration...");
      console.log(`  Gateway port: ${detectedPort}`);
      console.log(`  PID source: openclaw-gateway.service (systemd)`);
      console.log(`  Memory threshold: 768MB`);
    } else {
      const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

      console.log("\n  OpenClaw Aegis — Setup Wizard\n");
      console.log("  Detected gateway config at ~/.openclaw/openclaw.json");
      console.log(`  Detected gateway port: ${detectedPort}\n`);

      const portStr = await ask(rl, "Gateway port", String(detectedPort));
      const port = parseInt(portStr, 10) || detectedPort;

      const memStr = await ask(rl, "Memory threshold (MB)", "768");
      const memThreshold = parseInt(memStr, 10) || 768;

      // Alert channels
      console.log("\n  Alert Channels (out-of-band — never through the gateway)\n");
      console.log("  Supported: ntfy, telegram, whatsapp, webhook\n");

      let addMore = true;
      while (addMore) {
        const channelType = await ask(rl, "Add alert channel? (ntfy/telegram/whatsapp/webhook/skip)", "skip");

        if (channelType === "skip" || channelType === "") {
          addMore = false;
          continue;
        }

        switch (channelType) {
          case "ntfy": {
            const topic = await ask(rl, "  ntfy topic", "aegis-alerts");
            const url = await ask(rl, "  ntfy server URL", "https://ntfy.sh");
            channels.push({ type: "ntfy", topic, url, priority: 4 });
            console.log(`  Added ntfy channel (${url}/${topic})\n`);
            break;
          }
          case "telegram": {
            const botToken = await ask(rl, "  Telegram bot token");
            const chatId = await ask(rl, "  Telegram chat ID");
            if (botToken && chatId) {
              channels.push({ type: "telegram", botToken, chatId });
              console.log("  Added Telegram channel\n");
            } else {
              console.log("  Skipped — bot token and chat ID required\n");
            }
            break;
          }
          case "whatsapp": {
            const phoneNumberId = await ask(rl, "  WhatsApp Business phone number ID");
            const accessToken = await ask(rl, "  WhatsApp Cloud API access token");
            const recipientNumber = await ask(rl, "  Recipient phone number (with country code, e.g. 61412345678)");
            if (phoneNumberId && accessToken && recipientNumber) {
              channels.push({ type: "whatsapp", phoneNumberId, accessToken, recipientNumber });
              console.log("  Added WhatsApp channel\n");
            } else {
              console.log("  Skipped — all three fields required\n");
            }
            break;
          }
          case "webhook": {
            const url = await ask(rl, "  Webhook URL");
            if (url) {
              const secret = await ask(rl, "  Webhook secret (optional)");
              const ch: { type: string; url: string; secret?: string } = { type: "webhook", url };
              if (secret) ch.secret = secret;
              channels.push(ch);
              console.log(`  Added webhook channel (${url})\n`);
            } else {
              console.log("  Skipped — URL required\n");
            }
            break;
          }
          default:
            console.log(`  Unknown channel type: ${channelType}\n`);
        }
      }

      rl.close();

      // Write config with user values
      const toml = generateToml({ port, memoryThresholdMb: memThreshold, channels });
      ensureConfigDir();
      fs.writeFileSync(configFile, toml, { mode: 0o600 });

      console.log(`\n  Config written to ${configFile}`);

      // Run a quick health check
      console.log("\n  Running health check...\n");
      const config = loadConfig(configFile);
      const monitor = new HealthMonitor(config);
      const score = await monitor.runAllProbes();

      const passed = score.probeResults.filter((p) => p.healthy).length;
      const failed = score.probeResults.filter((p) => !p.healthy);

      console.log(`  Health: ${score.band.toUpperCase()} (${passed}/${score.probeResults.length} probes passed)`);
      if (failed.length > 0) {
        for (const probe of failed) {
          console.log(`    - ${probe.name}: ${probe.message ?? "failed"}`);
        }
      }

      if (channels.length === 0) {
        console.log("\n  No alert channels configured. You can add them later by editing:");
        console.log(`  ${configFile}`);
      }

      console.log("\n  Setup complete. Run 'aegis check' to verify anytime.\n");
      return;
    }

    // Auto mode write
    const toml = generateToml({ port: detectedPort, memoryThresholdMb: 768, channels });
    ensureConfigDir();
    fs.writeFileSync(configFile, toml, { mode: 0o600 });
    console.log(`Config written to ${configFile}`);

    const config = loadConfig(configFile);
    const monitor = new HealthMonitor(config);
    const score = await monitor.runAllProbes();
    const passed = score.probeResults.filter((p) => p.healthy).length;
    console.log(`Health: ${score.band.toUpperCase()} (${passed}/${score.probeResults.length} probes passed)`);
    console.log("\nSetup complete.");
  });
